[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "ItoLab"
version = "0.1.0"
description = "Stochastic process simulation library accompanying the Stochastic Finance book."
readme = "README.md"
requires-python = ">=3.12"

authors = [
    {name = "Erik Heitfield"}
]

dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]